baseURL = 'https://jonczy.pl/til'
languageCode = 'en-us'
title = 'Today I Learned'

theme = "hugo-theme-yinyang"


[params]
  author = "Robert Jonczy"
  description = "Robert blogs what learned today"
  headTitle = "Today I Learned"
  mainSections = ["posts"]

  [[params.social]]
    icon = "github"
    name = "GitHub"
    url = "https://github.com/rjonczy"

  [[params.social]]
    icon = "twitter"
    name = "Twitter"
    url = "https://twitter.com/robertjonczy"