baseURL = 'https://til.jonczy.pl/'
languageCode = 'en-us'
title = 'Today I Learned'

theme = "hugo-theme-yinyang"


[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
  [markup.highlight]
    guessSyntax = true
    noClasses = true
    style = "tango"
    tabWidth = 2

[author]
  name = "Robert Jonczy"
  homepage = "https://til.jonczy.pl/"


[params]
  author = "Robert Jonczy"
  description = "Robert blogs what learned today"
  headTitle = "Today I Learned"
  mainSections = ["posts"]

[[params.socials]]
name = "GitHub"
link = "https://github.com/rjonczy"

[[params.socials]]
name = "Twitter"
link = "https://twitter.com/robertjonczy"
